# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cRr8y0fKG9fUiGdwX4xExbV33a5-ZCPt
"""

import streamlit as st
import numpy as np
import plotly.graph_objects as go

# -----------------------------
# CONFIG
# -----------------------------
st.set_page_config(page_title="Spectral Trainer", layout="wide")

# -----------------------------
# UI STYLE (GRADIENT + GLOW)
# -----------------------------
st.markdown("""
<style>
body {
    background: linear-gradient(135deg, #0f172a, #1e293b, #020617);
    color: white;
}
h1, h2, h3 {
    text-align: center;
}
.card {
    background: rgba(255,255,255,0.05);
    padding: 20px;
    border-radius: 20px;
    margin-bottom: 20px;
}
.metric {
    background: linear-gradient(135deg, #2563eb, #7c3aed);
    padding: 15px;
    border-radius: 15px;
    text-align: center;
    font-weight: bold;
}
</style>
""", unsafe_allow_html=True)

# -----------------------------
# SESSION STATE
# -----------------------------
if "score" not in st.session_state:
    st.session_state.score = 0
    st.session_state.total = 0
    st.session_state.streak = 0
    st.session_state.index = 0
    st.session_state.show_explain = False

# -----------------------------
# HEADER
# -----------------------------
st.markdown("## ✦ Train Your Eye")
st.markdown("### Phase 1 — Recognize NORMAL spectra")

# -----------------------------
# DATA (20 CASES)
# -----------------------------
def generate_cases():
    x = np.linspace(0, 100, 500)

    base = np.exp(-(x - 30)**2 / 50) + 0.7*np.exp(-(x - 60)**2 / 80)

    cases = []

    # NORMAL
    cases.append((base, True, "Clean"))
    cases.append((base*1.1, True, "Intensity"))
    cases.append((np.exp(-(x - 40)**2 / 60), True, "Single peak"))
    cases.append((base + 0.02*np.random.randn(len(x)), True, "Low noise"))
    cases.append((base*0.8, True, "Scaled"))

    # DISTORTED
    cases.append((base + np.random.normal(0,0.2,len(x)), False, "Noise"))
    cases.append((base + 0.3*(x/max(x)), False, "Drift"))
    cases.append((base - 0.3*(x/max(x)), False, "Negative drift"))
    cases.append((base + 0.1*np.sin(x/5), False, "Wavy"))
    cases.append((np.clip(base*3,0,1), False, "Saturation"))
    cases.append((base + 0.5, False, "Offset"))

    shift = np.exp(-(x-40)**2/50) + 0.7*np.exp(-(x-70)**2/80)
    cases.append((shift, False, "Shift"))

    cases.append((base*0.3, False, "Flatten"))
    cases.append((base*(1+0.3*np.random.randn(len(x))), False, "Mult noise"))
    cases.append((base + 0.2*np.random.randn(len(x)) + 0.3*(x/max(x)), False, "Mixed"))

    return x, cases

x, cases = generate_cases()
y, is_normal, label = cases[st.session_state.index]

# -----------------------------
# 3D-LIKE PLOT (PLOTLY)
# -----------------------------
fig = go.Figure()

fig.add_trace(go.Scatter3d(
    x=x,
    y=y,
    z=np.zeros_like(x),
    mode='lines',
    line=dict(width=6)
))

fig.update_layout(
    scene=dict(
        xaxis_title='Wavelength',
        yaxis_title='Intensity',
        zaxis=dict(visible=False),
        bgcolor='black'
    ),
    margin=dict(l=0, r=0, t=0, b=0),
)

st.plotly_chart(fig, use_container_width=True)

# -----------------------------
# USER INPUT
# -----------------------------
st.markdown("### 🧠 Your Decision")

choice = st.radio("Is it NORMAL?", ["Normal", "Not Normal"], horizontal=True)

# -----------------------------
# VALIDATION
# -----------------------------
if st.button("✔ Validate"):

    st.session_state.total += 1
    st.session_state.show_explain = True

    correct = (
        (choice == "Normal" and is_normal) or
        (choice == "Not Normal" and not is_normal)
    )

    if correct:
        st.success("✔ Correct")
        st.session_state.score += 1
        st.session_state.streak += 1
    else:
        st.error("✖ Wrong")
        st.session_state.streak = 0

# -----------------------------
# EXPLANATION + CHECKLIST
# -----------------------------
if st.session_state.show_explain:

    st.markdown("## 🔍 Visual Justification")

    # highlight baseline
    baseline = np.mean(y)
    st.line_chart(y)

    st.markdown("### ✔ Checklist")

    # checklist logic
    smooth = np.std(np.diff(y)) < 0.1
    flat = abs(np.polyfit(x, y, 1)[0]) < 0.01
    peaks = np.max(y) > np.mean(y)

    if smooth:
        st.success("✔ Smooth signal")
    else:
        st.error("✖ Too noisy")

    if flat:
        st.success("✔ Flat baseline")
    else:
        st.error("✖ Baseline drift")

    if peaks:
        st.success("✔ Clear peaks")
    else:
        st.error("✖ No clear peaks")

    if is_normal:
        st.info("👉 NORMAL = smooth + stable + clear peaks")
    else:
        st.info(f"👉 NOT NORMAL → {label}")

# -----------------------------
# NEXT
# -----------------------------
if st.button("➡ Next"):
    st.session_state.index += 1
    if st.session_state.index >= len(cases):
        st.session_state.index = 0
    st.session_state.show_explain = False
    st.rerun()

# -----------------------------
# SCORE
# -----------------------------
st.markdown("## 📊 Performance")

accuracy = (st.session_state.score / st.session_state.total * 100) if st.session_state.total else 0

c1, c2, c3 = st.columns(3)

c1.markdown(f'<div class="metric">Score<br>{st.session_state.score}</div>', unsafe_allow_html=True)
c2.markdown(f'<div class="metric">Accuracy<br>{accuracy:.1f}%</div>', unsafe_allow_html=True)
c3.markdown(f'<div class="metric">Streak 🔥<br>{st.session_state.streak}</div>', unsafe_allow_html=True)

# -----------------------------
# PROGRESS
# -----------------------------
progress = (st.session_state.index + 1) / len(cases)
st.progress(progress)
st.caption(f"Case {st.session_state.index + 1} / {len(cases)}")