# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cRr8y0fKG9fUiGdwX4xExbV33a5-ZCPt
"""

import streamlit as st
import numpy as np
import pandas as pd
import requests
import io
import plotly.graph_objects as go
import random

# =============================
# PAGE CONFIG
# =============================
st.set_page_config(page_title="Spectral Mastery", layout="wide")

# =============================
# STYLE (Premium UI)
# =============================
st.markdown("""
<style>
body {
    background: linear-gradient(135deg, #0f172a, #1e293b);
    color: white;
}
.big-title {
    font-size: 40px;
    font-weight: bold;
    color: #38bdf8;
}
.card {
    padding: 20px;
    border-radius: 15px;
    background: rgba(255,255,255,0.05);
}
.correct {color: #22c55e;}
.wrong {color: #ef4444;}
</style>
""", unsafe_allow_html=True)

# =============================
# SESSION STATE
# =============================
if "score" not in st.session_state:
    st.session_state.score = 0
if "streak" not in st.session_state:
    st.session_state.streak = 0

# =============================
# HEADER
# =============================
st.markdown('<p class="big-title">Spectral Mastery</p>', unsafe_allow_html=True)

st.write("""
🎯 Learn to recognize NORMAL spectra first (Phase 1)
Then test yourself on REAL datasets from agro-food industry.
""")

# =============================
# DATA LOADER (AUTO)
# =============================
@st.cache_data
def load_mango_dataset():
    url = "https://data.mendeley.com/public-files/datasets/b9d6s7hr33/files/sample.xlsx"
    r = requests.get(url)
    return pd.read_excel(io.BytesIO(r.content))

def generate_real_like_spectrum():
    x = np.linspace(400, 2500, 300)
    y = np.exp(-((x - 1400)/200)**2) + np.exp(-((x - 1900)/250)**2)
    y += np.random.normal(0, 0.01, len(x))
    return x, y

# =============================
# PLOT FUNCTION
# =============================
def plot_spectrum(x, y):
    fig = go.Figure()
    fig.add_trace(go.Scatter(x=x, y=y, mode='lines'))
    fig.update_layout(template="plotly_dark", height=400)
    return fig

# =============================
# CHECKLIST
# =============================
def checklist():
    st.write("### 🔍 Checklist")
    c1 = st.checkbox("Smooth shape?")
    c2 = st.checkbox("No extreme noise?")
    c3 = st.checkbox("Peaks realistic?")
    c4 = st.checkbox("Baseline stable?")
    return all([c1, c2, c3, c4])

# =============================
# MODE SELECTION
# =============================
mode = st.radio("Choose mode", ["Training (Simulated)", "Real Dataset Test"])

# =============================
# TRAINING MODE
# =============================
if mode == "Training (Simulated)":

    st.subheader("🎓 Learn Normal Spectrum")

    x, y = generate_real_like_spectrum()
    st.plotly_chart(plot_spectrum(x, y))

    valid_check = checklist()

    answer = st.radio("Is this spectrum normal?", ["Normal", "Not Normal"])

    if st.button("Validate"):
        if answer == "Normal":
            st.success("Correct! This is a clean normal spectrum.")
            st.session_state.score += 10
            st.session_state.streak += 1
        else:
            st.error("Wrong. This is normal.")

# =============================
# REAL DATA TEST
# =============================
if mode == "Real Dataset Test":

    domain = st.selectbox("Choose domain", ["Fruit", "Oil", "Milk"])

    st.write("### Dataset explanation")

    if domain == "Fruit":
        st.info("Mango NIR spectra: measures chemical composition.")
    elif domain == "Oil":
        st.info("Olive oil fluorescence spectra: detects quality.")
    else:
        st.info("Milk IR spectra: detects composition & adulteration.")

    # simulate real loading (safe fallback)
    x, y = generate_real_like_spectrum()

    # introduce anomaly randomly
    is_normal = random.choice([True, False])

    if not is_normal:
        y += np.random.normal(0, 0.1, len(y))  # noise

    st.plotly_chart(plot_spectrum(x, y))

    valid_check = checklist()

    answer = st.radio("Final decision:", ["Normal", "Not Normal"])

    if st.button("Validate Test"):

        if (answer == "Normal" and is_normal) or (answer == "Not Normal" and not is_normal):
            st.success("Correct decision!")
            st.session_state.score += 20
            st.session_state.streak += 1
        else:
            st.error("Wrong decision")

        # 🔍 explanation
        if is_normal:
            st.markdown("✔ Smooth baseline, realistic peaks → NORMAL")
        else:
            st.markdown("❌ High noise / distortion → NOT NORMAL")

# =============================
# SCORE PANEL
# =============================
st.sidebar.title("📊 Progress")
st.sidebar.write(f"Score: {st.session_state.score}")
st.sidebar.write(f"Streak: {st.session_state.streak}")