# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cRr8y0fKG9fUiGdwX4xExbV33a5-ZCPt
"""

import streamlit as st
import numpy as np
import plotly.graph_objects as go
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

from utils import generate_spectrum, load_real_dataset

# -------------------------
# CONFIG
# -------------------------
st.set_page_config(page_title="Chemometrics Trainer", layout="wide")

# -------------------------
# SESSION STATE
# -------------------------
if "score" not in st.session_state:
    st.session_state.score = 0

if "spectrum" not in st.session_state:
    st.session_state.spectrum = generate_spectrum()

# -------------------------
# TITLE
# -------------------------
st.title("🧠 Chemometrics Training Platform")
st.caption("From Spectra → PCA → Real Data Intelligence")

# -------------------------
# SIDEBAR MODE
# -------------------------
mode = st.sidebar.selectbox(
    "Select Mode",
    ["Training Mode", "Real Dataset Mode", "PCA Explorer"]
)

# =========================================================
# 1. TRAINING MODE (INTUITION)
# =========================================================
if mode == "Training Mode":

    x, y, label = st.session_state.spectrum

    fig = go.Figure()
    fig.add_trace(go.Scatter(x=x, y=y, mode="lines"))

    fig.update_layout(template="plotly_dark", height=400)

    st.plotly_chart(fig, use_container_width=True)

    decision = st.radio("Is this spectrum normal?", ["Normal", "Not Normal"])

    if st.button("Validate"):

        correct = (label and decision == "Normal") or (not label and decision == "Not Normal")

        if correct:
            st.success("Correct analysis")
            st.session_state.score += 10
        else:
            st.error("Incorrect interpretation")

        st.session_state.spectrum = generate_spectrum()
        st.rerun()

# =========================================================
# 2. REAL DATA MODE (MENDELEY DATA)
# =========================================================
elif mode == "Real Dataset Mode":

    st.subheader("🌍 Real Spectral Dataset")

    df, X = load_real_dataset()

    st.write("Shape:", X.shape)

    sample = st.selectbox("Select sample", list(range(len(X))))

    spectrum = X[sample]

    fig = go.Figure()
    fig.add_trace(go.Scatter(y=spectrum, mode="lines"))

    fig.update_layout(template="plotly_dark")

    st.plotly_chart(fig, use_container_width=True)

# =========================================================
# 3. PCA EXPLORER (CHEMOMETRICS CORE)
# =========================================================
elif mode == "PCA Explorer":

    st.subheader("📊 PCA Analysis (Chemometrics Core)")

    df, X = load_real_dataset()

    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)

    pca = PCA(n_components=2)
    X_pca = pca.fit_transform(X_scaled)

    fig = go.Figure()

    fig.add_trace(go.Scatter(
        x=X_pca[:, 0],
        y=X_pca[:, 1],
        mode="markers",
        marker=dict(color="cyan")
    ))

    fig.update_layout(
        template="plotly_dark",
        xaxis_title="PC1",
        yaxis_title="PC2"
    )

    st.plotly_chart(fig, use_container_width=True)

    st.info("PCA reveals structure, clusters, and outliers in spectral data.")