# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cRr8y0fKG9fUiGdwX4xExbV33a5-ZCPt
"""

import streamlit as st
import numpy as np
import matplotlib.pyplot as plt

# -----------------------------
# CONFIG
# -----------------------------
st.set_page_config(
    page_title="Spectral Trainer",
    layout="wide",
    initial_sidebar_state="collapsed"
)

# -----------------------------
# PREMIUM UI
# -----------------------------
st.markdown("""
<style>
body {
    background: linear-gradient(135deg, #0f172a, #1e293b);
    color: white;
}
.block-container {
    padding-top: 2rem;
}
h1, h2, h3 {
    text-align: center;
}
.card {
    background: rgba(255,255,255,0.05);
    padding: 20px;
    border-radius: 20px;
    margin-bottom: 20px;
}
.metric-box {
    background: linear-gradient(135deg, #2563eb, #7c3aed);
    padding: 15px;
    border-radius: 15px;
    text-align: center;
    color: white;
    font-weight: bold;
}
button {
    border-radius: 12px !important;
    height: 3em;
    font-weight: bold;
}
</style>
""", unsafe_allow_html=True)

# -----------------------------
# SESSION STATE
# -----------------------------
if "score" not in st.session_state:
    st.session_state.score = 0
    st.session_state.total = 0
    st.session_state.streak = 0
    st.session_state.index = 0

# -----------------------------
# HEADER
# -----------------------------
st.markdown("## ✦ Learn to SEE Spectra")
st.markdown("### Phase 1 — Normal vs Not Normal")

# -----------------------------
# GENERATE 20 CASES
# -----------------------------
def generate_cases():
    x = np.linspace(0, 100, 500)

    base = (
        np.exp(-(x - 30)**2 / 50)
        + 0.7 * np.exp(-(x - 60)**2 / 80)
    )

    cases = []

    # -------- NORMAL (5) --------
    cases.append((base, True, "Clean spectrum"))
    cases.append((base * 1.1, True, "Higher intensity"))
    cases.append((np.exp(-(x - 40)**2 / 60), True, "Single peak"))
    cases.append((base + 0.02*np.random.randn(len(x)), True, "Very low noise"))
    cases.append((base * 0.8, True, "Lower intensity"))

    # -------- DISTORTED (15) --------
    cases.append((base + np.random.normal(0, 0.2, len(x)), False, "High noise"))
    cases.append((base + np.random.normal(0, 0.4, len(x)), False, "Extreme noise"))
    cases.append((base + 0.3*(x/max(x)), False, "Baseline drift"))
    cases.append((base + 0.6*(x/max(x)), False, "Strong drift"))
    cases.append((base - 0.3*(x/max(x)), False, "Negative drift"))

    shift = np.exp(-(x - 40)**2 / 50) + 0.7*np.exp(-(x - 70)**2 / 80)
    cases.append((shift, False, "Peak shift"))

    cases.append((base * 0.3, False, "Flattened peaks"))
    cases.append((np.clip(base * 3, 0, 1), False, "Saturation"))
    cases.append((base + 0.1*np.sin(x/5), False, "Wavy baseline"))

    spikes = base.copy()
    spikes[::20] += 0.5
    cases.append((spikes, False, "Spikes"))

    cases.append((base + 0.5, False, "Offset baseline"))
    cases.append((base * (1 + 0.3*np.random.randn(len(x))), False, "Multiplicative noise"))

    broad = np.exp(-(x - 30)**2 / 150)
    cases.append((broad, False, "Peak broadening"))

    weird = base + 0.2*np.sin(x)
    cases.append((weird, False, "Shape distortion"))

    mixed = base + 0.2*np.random.randn(len(x)) + 0.3*(x/max(x))
    cases.append((mixed, False, "Mixed distortion"))

    return x, cases

x, cases = generate_cases()
y, is_normal, explanation = cases[st.session_state.index]

# -----------------------------
# PLOT
# -----------------------------
st.markdown('<div class="card">', unsafe_allow_html=True)

fig, ax = plt.subplots()
ax.plot(x, y, linewidth=2)

ax.set_facecolor("#0f172a")
fig.patch.set_facecolor("#0f172a")

ax.set_xlabel("Wavelength", color="white")
ax.set_ylabel("Intensity", color="white")
ax.tick_params(colors='white')

st.pyplot(fig)
st.markdown('</div>', unsafe_allow_html=True)

# -----------------------------
# USER INPUT
# -----------------------------
st.markdown("### 🧠 Your Decision")

choice = st.radio(
    "Is this spectrum NORMAL?",
    ["Normal", "Not Normal"],
    horizontal=True
)

col1, col2 = st.columns(2)

with col1:
    validate = st.button("✔ Validate")

with col2:
    next_case = st.button("➡ Next")

# -----------------------------
# VALIDATION
# -----------------------------
if validate:
    st.session_state.total += 1

    correct = (
        (choice == "Normal" and is_normal) or
        (choice == "Not Normal" and not is_normal)
    )

    if correct:
        st.success("✨ Perfect! You are training your eye.")
        st.session_state.score += 1
        st.session_state.streak += 1
    else:
        st.error("⚠ Not correct")

        if is_normal:
            st.info("👉 This is NORMAL: smooth + stable + clear peaks")
        else:
            st.info("👉 This is NOT normal: something disturbs the signal")

        st.session_state.streak = 0

    st.caption(f"🔍 Hidden case: {explanation}")

# -----------------------------
# NEXT CASE
# -----------------------------
if next_case:
    st.session_state.index += 1

    if st.session_state.index >= len(cases):
        st.session_state.index = 0

    st.rerun()

# -----------------------------
# METRICS
# -----------------------------
st.markdown("### 📊 Performance")

accuracy = (
    st.session_state.score / st.session_state.total * 100
    if st.session_state.total > 0 else 0
)

col1, col2, col3 = st.columns(3)

with col1:
    st.markdown(f'<div class="metric-box">Score<br>{st.session_state.score}</div>', unsafe_allow_html=True)

with col2:
    st.markdown(f'<div class="metric-box">Accuracy<br>{accuracy:.1f}%</div>', unsafe_allow_html=True)

with col3:
    st.markdown(f'<div class="metric-box">Streak 🔥<br>{st.session_state.streak}</div>', unsafe_allow_html=True)

# -----------------------------
# PROGRESS BAR
# -----------------------------
progress = (st.session_state.index + 1) / len(cases)
st.progress(progress)
st.caption(f"Case {st.session_state.index + 1} / {len(cases)}")