# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cRr8y0fKG9fUiGdwX4xExbV33a5-ZCPt
"""

import streamlit as st

# Page config
st.set_page_config(
    page_title="Identify Normal Spectra",
    layout="wide"
)

# --- Custom CSS (THIS is what creates the design) ---
st.markdown("""
<style>

/* Remove default padding */
.block-container {
    padding-top: 0rem;
    padding-bottom: 0rem;
    padding-left: 2rem;
    padding-right: 2rem;
}

/* Full hero section */
.hero {
    height: 90vh;
    display: flex;
    align-items: center;
    justify-content: space-between;
}

/* Left text */
.hero-text {
    max-width: 50%;
}

/* Title */
.title {
    font-size: 64px;
    font-weight: 600;
    line-height: 1.1;
}

/* Subtitle */
.subtitle {
    font-size: 20px;
    color: #555;
    margin-top: 10px;
    margin-bottom: 30px;
}

/* Button */
.cta-button {
    background-color: #e6d3a3;
    padding: 12px 30px;
    border-radius: 25px;
    font-weight: 600;
    border: none;
}

/* Feature list */
.features {
    margin-top: 40px;
    font-size: 18px;
}

.features li {
    margin-bottom: 12px;
}

/* Check list */
.checks {
    margin-top: 30px;
    font-size: 18px;
    color: #2e7d32;
}

/* Right image */
.hero-img img {
    width: 100%;
    border-radius: 12px;
}

</style>
""", unsafe_allow_html=True)

# --- Layout ---
col1, col2 = st.columns([1, 1])

with col1:
    st.markdown('<div class="hero-text">', unsafe_allow_html=True)

    st.markdown('<div class="title">Identify Normal Spectra</div>', unsafe_allow_html=True)

    st.markdown('<div class="subtitle">Work with real datasets like a game</div>', unsafe_allow_html=True)

    # CTA Button
    if st.button("🚀 Try It Now"):
        st.success("App Started!")

    # Features
    st.markdown("""
    <div class="features">
    <ol>
        <li><b>SEE spectra</b></li>
        <li><b>UNDERSTAND patterns</b></li>
        <li><b>DETECT anomalies</b></li>
        <li><b>APPLY knowledge to real data</b></li>
    </ol>
    </div>
    """, unsafe_allow_html=True)

    # Check marks
    st.markdown("""
    <div class="checks">
    ✔ Intuitive<br>
    ✔ Interactive<br>
    ✔ Scientifically grounded
    </div>
    """, unsafe_allow_html=True)

    st.markdown('</div>', unsafe_allow_html=True)


with col2:
    st.markdown('<div class="hero-img">', unsafe_allow_html=True)

    # Replace with your own image if you want
    st.image("https://images.unsplash.com/photo-1551288049-bebda4e38f71")

    st.markdown('</div>', unsafe_allow_html=True)


# --- Optional: Next section (app simulation) ---
st.markdown("---")

st.header("🎮 Try the Spectrum Game")

import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(400, 800, 200)
y = np.exp(-0.01*(x-550)**2) + 0.1*np.random.rand(200)

fig, ax = plt.subplots()
ax.plot(x, y)
ax.set_title("Sample Spectrum")
ax.set_xlabel("Wavelength (nm)")
ax.set_ylabel("Intensity")

st.pyplot(fig)

st.info("Can you detect if this spectrum is normal?")