# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cRr8y0fKG9fUiGdwX4xExbV33a5-ZCPt
"""

import streamlit as st
import numpy as np
import matplotlib.pyplot as plt
from scipy.signal import find_peaks, savgol_filter



st.markdown("## ✦ Chemometrics for All")
st.markdown("### Spectral Quality Visual Checker")

st.info("Train your eye before modeling spectral data.")
st.set_page_config(page_title="Spectral Checklist", layout="centered")

st.title(" Spectral Quality Checklist")

# -----------------------------
# Generate or upload spectrum
# -----------------------------
option = st.radio("Choose data source:", ["Simulated Spectrum"])

if option == "Simulated Spectrum":
    x = np.linspace(0, 100, 500)

    # Create a "normal" spectrum
    y = (
        np.exp(-(x - 30)**2 / 50)
        + 0.7 * np.exp(-(x - 60)**2 / 80)
    )

    noise_level = st.slider("Noise level", 0.0, 0.5, 0.05)
    drift = st.slider("Baseline drift", 0.0, 0.5, 0.0)

    noise = np.random.normal(0, noise_level, len(x))
    baseline = drift * (x / max(x))

    y = y + noise + baseline


# -----------------------------
# Plot spectrum
# -----------------------------
st.subheader("📈 Spectrum")
fig, ax = plt.subplots()
ax.plot(x, y)
ax.set_xlabel("Wavelength")
ax.set_ylabel("Intensity")
st.pyplot(fig)

# -----------------------------
# CHECKLIST LOGIC
# -----------------------------

st.subheader("🧠 Checklist Diagnosis")

# 1. Noise estimation
smooth = savgol_filter(y, 21, 3)
noise = np.std(y - smooth)

# 2. Baseline estimation
baseline_trend = np.polyfit(x, y, 1)[0]

# 3. Peak detection
peaks, _ = find_peaks(y, height=np.mean(y))

# -----------------------------
# Results
# -----------------------------

def check(condition, label):
    if condition:
        st.success(f"✔ {label}")
    else:
        st.error(f"⚠ {label}")

# Apply rules
check(len(peaks) > 0, "Clear Peaks detected")

check(abs(baseline_trend) < 0.01, "Flat Baseline")

check(noise < 0.1, "Low Noise")

check(len(peaks) >= 2, "Consistent Peak Structure")

# Final decision
st.subheader("📊 Final Verdict")

if (len(peaks) > 0) and (abs(baseline_trend) < 0.01) and (noise < 0.1):
    st.success("✅ NORMAL SPECTRUM")
else:
    st.error("🚨 DISTORTED SPECTRUM")

# -----------------------------
# Show metrics
# -----------------------------
st.subheader("📌 Metrics")

st.write(f"Noise level: {noise:.4f}")
st.write(f"Baseline slope: {baseline_trend:.4f}")
st.write(f"Number of peaks: {len(peaks)}")