# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cRr8y0fKG9fUiGdwX4xExbV33a5-ZCPt
"""

import numpy as np
import pandas as pd

# -------------------------
# SIMULATED SPECTRUM
# -------------------------
def generate_spectrum():
    x = np.linspace(1000, 2500, 400)
    y = np.exp(-((x - 1700) ** 2) / 60000)

    label = np.random.choice([True, False])

    if not label:
        y += np.random.normal(0, 0.05, len(x))
        y += np.linspace(0, 0.2, len(x))

    return x, y, label


# -------------------------
# REAL DATA LOADER
# -------------------------
def load_real_dataset():

    # Replace this with real Mendeley CSV later
    # Each row = spectrum

    n_samples = 50
    n_features = 200

    X = np.zeros((n_samples, n_features))

    for i in range(n_samples):
        base = np.exp(-((np.linspace(0, 1, n_features) - 0.5) ** 2) / 0.02)
        noise = np.random.normal(0, 0.02, n_features)
        X[i] = base + noise + (i * 0.001)

    return None, X